### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Thelopik** [sebinside/YouTubeChatOverflow#4]
Womit programmiert ihr da eigentlich? 
Und könnt ihr mal Schwarz beim Licht ausprobieren?

**Comment by Falseee** [comment]
@Thelopik 
Programmiert wird in Scala, ein Schwarz wäre in rgb 0, 0, 0.
Würde man jedoch 0, 0, 0 benutzen würden die LEDs einfach ausgehen.

**Comment by asffsasafsaf** [comment]
@Falseee es gibt 4 werte... W, X, Y, Z... ich schätze mal wert W ist wie stark die Lampen leuchten...

**Comment by Falseee** [comment]
@asffsasafsaf
Schwarz ist nicht möglich, habe selber über meinem Pi eine LED Strip laufen.
