### ISSUE TITLE
MinecraftControl

### ISSUE THREAD

**Issue by Falseee** [sebinside/YouTubeChatOverflow#6]
In einem älteren Video sagtest du mal man könnte ein Mod schreiben der von Extern Sachen annimmt und damit dann etwas macht.
Wäre es nicht besser ein Mod zu schreiben der die Wörter "up", "down" etc annimmt und dann der Client sagt "geh vorwärts"?
Somit könnte man nebenbei noch Sachen machen :p

**Comment by sebinside** [comment]
Das ist korrekt, so könnte man Minecraft direkt steuern. In unserem Fall haben wir uns aber für die schnelle und einfache Lösung der externen Steuerung entschieden, da die direkte Steuerung mit Hilfe einer Folge Mod wesentlich aufwendiger ist :)
