### ISSUE TITLE
client_secrets.json

### ISSUE THREAD

**Issue by Ullmie02** [sebinside/YouTubeChatOverflow#8]
Wie muss die Datei client_secrets.json aufgebaut sein?

**Comment by Falseee** [comment]
Ich schätze mal damit ist diese gemeint: https://developers.google.com/api-client-library/python/guide/aaa_client_secrets

**Comment by sebinside** [comment]
Die client_secrets.json erhält man von der Google Developer Seite nach dem Anlegen eines neuen Projekts. Ein bisschen aufwendig die richtige Seite zu finden, aber ohne weiteres für jeden möglich :)
